default_context:
  project_name: 'Open_API'
  project_slug: 'open_api'
  domain_main: 'open-api.mn'
  domain_staging: 'stag.open-api.mn'
  docker_swarm_stack_name_main: 'open-api-mn'
  docker_swarm_stack_name_staging: 'stag-open-api-mn'
  secret_key: 'S2ec@#T'
  first_superuser: 'root'
  first_superuser_password: 'S2ec@#T'
  backend_cors_origins: 'http://open-api.mn'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@open-api.mn'
  postgres_password: 'Open@123'
  pgadmin_default_user: 'tech_choijilbuu'
  pgadmin_default_user_password: 'Open@123'
  traefik_constraint_tag: 'open-api.mn'
  traefik_constraint_tag_staging: 'stag.open-api.mn'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:S2ec@#T'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
